# Generated by Django 5.0.2 on 2024-03-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0003_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='SignupForm',
        ),
    ]
